name: Label Pull Requests
on:
  pull_request:
    types: [opened]
jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Label pull_requests
        uses: andymckay/labeler@master
        with:
          add-labels: "do not merge"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
