name: remove label
on:
  pull_request_review:
    types:
      - converted_to_draft
jobs:
  remove_label:
    runs-on: ubuntu-latest
    name: remove label
    steps:
      - name: removelabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: DO NOT MERGE
          type: remove
