name: Label pull requests
on:
  pull_requests:
    types:
      - reopened
      - opened
jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      pull_requests: write
    steps:
      - name: Label pull_requests
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "DO NOT MERGE"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
