name: Remove "DO NOT MERGE" label
on:
  pull_request:
    types:
      - opened
jobs:
  remove_do_not_merge_label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: andymckay/labeler@master
        with:
          remove-labels: "DO NOT MERGE"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
